services:
  - type: worker
    name: fushiguro-anime-catcher
    env: docker
    plan: free
    envVars:
      - key: BOT_NAME
        value: Anime Catcher
      - key: OWNER_NAME
        value: fushiguro
        
